src/main/java/controlador/LibroController.java
package controlador;

import entidades.Libro;
import controlador.util.JsfUtil;
import controlador.util.PaginationHelper;
import accesoDatos.LibroFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import jakarta.ejb.EJB;
import jakarta.inject.Named;
import jakarta.enterprise.context.SessionScoped;
import jakarta.faces.component.UIComponent;
import jakarta.faces.context.FacesContext;
import jakarta.faces.convert.Converter;
import jakarta.faces.convert.FacesConverter;
import jakarta.faces.model.DataModel;
import jakarta.faces.model.ListDataModel;
import jakarta.faces.model.SelectItem;



@Named("libroController")
@SessionScoped
public class LibroController implements Serializable {

    private Libro current;
    private DataModel items = null;
    @EJB
    private accesoDatos.LibroFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    private String search;
    private boolean advertencia;
    private String titulo;

    public LibroController() {
        search = "";
        //advertencia = true;
    }

    public Libro getSelected() {
        if (current == null) {
            current = new Libro();
            selectedItemIndex = -1;
        }
        return current;
    }

    private LibroFacade getFacade() {
        return ejbFacade;
    }

    public String getSearch() {
        return search;
    }

    public void setSearch(String search) {
        this.search = search;
    }
    

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(5) {

                @Override
                public int getItemsCount() {
                    return getFacade().find(search).size();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()-1},search));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Libro) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        advertencia = false;
        current = new Libro();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        List<Libro> libros = ejbFacade.find(current.getTitulo(), current.getIdAutor().getAutor(), current.getIdEditorial().getEditorial(), current.getIsbn());
        
        if(libros.isEmpty()){
        try {
            advertencia = false;
            if(current.getCantidadDisponible()>0)
                current.setStatus(1);
            else 
                current.setStatus(0);
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("LibroCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }}else{
            JsfUtil.addErrorMessage(new Exception(), "Error de duplicidad, el libro ya esta registrado con los mismos valores.");
            advertencia = true;
            current = libros.get(0);
            return null;
        }
        
    }

    public String prepareEdit() {
        current = (Libro) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            Libro l = getFacade().find(current.getId());
            int cant = current.getCantidad()-l.getCantidad();
            System.out.println("La cantidad es: "+ cant);
            current.setCantidadDisponible(current.getCantidadDisponible()+cant);
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("LibroUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Libro) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }
    public String show() {
        recreateModel();
        getItems();
        return "List";
    }
    public String showAll() {
        search="";
        recreateModel();
        getItems();
        return "List";
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.info(ResourceBundle.getBundle("/Bundle").getString("LibroDeleted"));
        } catch (Exception e) {
            JsfUtil.error(ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Libro getLibro(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Libro.class)
    public static class LibroControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            LibroController controller = (LibroController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "libroController");
            return controller.getLibro(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Libro) {
                Libro o = (Libro) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Libro.class.getName());
            }
        }
        

    }
    public String salir(){
        advertencia = false;
        return "List";
    }
    public String actualizar(){
        advertencia = false;
        return "EditExistencias";
    }

    public boolean isAdvertencia() {
        return advertencia;
    }

    public void setAdvertencia(boolean advertencia) {
        this.advertencia = advertencia;
    }
    
    public void comprobarL(){
        List<Libro> libros = ejbFacade.find(current.getTitulo(), current.getIdAutor().getAutor());
        advertencia = !libros.isEmpty();
        if(!libros.isEmpty())
            current = libros.get(0);
    }

    public int getSelectedItemIndex() {
        return selectedItemIndex;
    }

    public void setSelectedItemIndex(int selectedItemIndex) {
        this.selectedItemIndex = selectedItemIndex;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    


    
    

}

src/main/webapp/libro/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">


    <ui:composition template="#{logueo.cambiarModoLT1()}">
        <ui:define name="title">
            <h:outputText value="Registrar un nuevo libro"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages infoClass="alert alert-success" errorClass="alert alert-danger"/>
            </h:panelGroup>
            <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
            </div>
            <div class="card-body">
            <div class="row">
                <div class="col-xl-7"> 
            <h:form id="RLibro">
                <p:panel rendered="#{libroController.advertencia}" id="adv" closable="true" toggleSpeed="500" closeSpeed="500" widgetVar="panel" style="margin-bottom:20px">
                    <f:facet name="header">
                        <h:outputText value="EL LIBRO YA ESTA REGISTRADO." style=" font-size: 18px; color: red;"/>
                     </f:facet>
                    <p:ajax event="close" listener="#{panelView.onClose}" update="RLibro:adv" />

                     <h:panelGrid columns="2" cellpadding="10">
                         <div class="row">
                             <div class="col-2">
                                 <img src="https://cdn-icons-png.flaticon.com/512/5219/5219070.png" width="100%" />
                             </div>
                             <div class="col-10">
                                 <label> El libro ya se encuentra actualmente registrado. Si sólo requiere cambiar el total de existencias, dea clic en <strong>actualizar</strong>.</label>
                             </div> 
                         </div>
                         <h:outputText/>
                         
                         <h:form>
                         <div class="btn-group">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                             <h:commandButton id="salir" class="btn btn-danger" value="Salir" action="#{libroController.salir()}" immediate="true" /> &nbsp;&nbsp;
                             <h:commandButton id="editar" class="btn btn-info" value="Actualizar" action="#{libroController.actualizar()}" immediate="true"/>
                         </div>
                         </h:form>
                     </h:panelGrid>

                </p:panel>
                <br/>
                <h:outputLabel>Para registrar la información de un nuevo libro es necesario que rellene los siguientes campos. Los campos obligatorios estan marcados con:  <span class="negrita" style="color:red; ">(*)</span></h:outputLabel>  
                <br/>
                    <br/>
                <h:panelGrid columns="3" class="col-xl-10">
                    <h:outputLabel class="form-label negrita" value="ID libro" for="id" />
                    <h:inputText class="form-control" id="id" value="#{libroController.selected.id}" disabled="true"/>
                    <p:tooltip for="id" value="#{bundle.EditLibroTitle_id}" position="right"/>
                    <h:outputLabel class="form-label negrita" value="#{bundle.EditLibroLabel_titulo}" for="titulo"><span class="negrita" style="color:red; ">(*)</span></h:outputLabel>
                    <p:inputText class="form-control" immediate="true" id="titulo" value="#{libroController.selected.titulo}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_titulo}">
                        <f:ajax execute="@this"/>
                    </p:inputText>
                    <p:tooltip for="titulo" value="#{bundle.EditLibroTitle_titulo}" position="right"/>
                    <h:outputLabel class="form-label negrita" value="#{bundle.EditLibroLabel_idAutor}" for="idAutor" ><span class="negrita" style="color:red; ">(*)</span></h:outputLabel>
                    <p:selectOneMenu filterMatchMode="contains"  style="width: 300px;" filter="true" filterPlaceholder="Autor" id="idAutor" value="#{libroController.selected.idAutor}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_idAutor}">
                        <f:selectItems value="#{autorController.itemsAvailableSelectOne}"/>
                        <p:ajax event="change"
                                update="RLibro" listener="#{libroController.comprobarL()}" oncomplete="$(function(){ PrimeFaces.focus('RLibro:titulo'); });">
                        </p:ajax>    
                    </p:selectOneMenu> 
                    <p:tooltip for="idAutor" value="#{bundle.EditLibroTitle_idAutor}" position="right"/>
                    <h:outputLabel class="form-label negrita" value="#{bundle.EditLibroLabel_idEditorial}" for="idEditorial" ><span class="negrita" style="color:red; ">(*)</span></h:outputLabel>
                    <p:selectOneMenu filterMatchMode="contains" style="width: 300px;" filter="true" filterPlaceholder="Editorial" id="idEditorial" value="#{libroController.selected.idEditorial}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_idEditorial}">
                        <f:selectItems value="#{editorialController.itemsAvailableSelectOne}"/>
                        <p:ajax process="idEditorial" event="change"
                                listener="#{libroController.comprobarL()}" update="RLibro"  >
                            <p:focus for="RLibro:adv"/>
                        </p:ajax>   
                    </p:selectOneMenu>
                    <p:tooltip for="idEditorial" value="#{bundle.EditLibroTitle_idEditorial}" position="right"/>
                    <h:outputLabel class="form-label negrita" value="#{bundle.EditLibroLabel_idMateria}" for="idMateria" ><span class="negrita" style="color:red; ">(*)</span></h:outputLabel>
                    <p:selectOneMenu filterMatchMode="contains" style="width: 300px;" filter="true" filterPlaceholder="Género" id="idMateria" value="#{libroController.selected.idMateria}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_idMateria}">
                        <f:selectItems value="#{materiaController.itemsAvailableSelectOne}"/>
                    </p:selectOneMenu>
                    <p:tooltip for="idMateria" value="#{bundle.EditLibroTitle_idMateria}" position="right"/>
                    <h:outputLabel class="form-label negrita" value="#{bundle.EditLibroLabel_cantidad}" for="cantidad"><span class="negrita" style="color:red; ">(*)</span></h:outputLabel>
                    <h:inputText class="form-control" id="cantidad" value="#{libroController.selected.cantidad}"  required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_cantidad}"/>
                    <p:tooltip for="cantidad" value="#{bundle.EditLibroTitle_cantidad}" position="right"/>
                    <h:outputLabel class="form-label negrita" value="#{bundle.EditLibroLabel_anioEdicion}" for="anioEdicion"><span class="negrita" style="color:red; ">(*)</span></h:outputLabel>
                    <p:calendar id="anioEdicion" value="#{libroController.selected.anioEdicion}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_anioEdicion}" showOn="button" locale="es">
                        <f:convertDateTime pattern="dd/MM/yyyy" />
                    </p:calendar>
                    <p:tooltip for="anioEdicion" value="#{bundle.EditLibroTitle_anioEdicion}"  position="right"/>
                    <h:outputLabel class="form-label negrita" value="#{bundle.EditLibroLabel_numPagina}" for="numPagina" />
                    <h:inputText class="form-control" id="numPagina" value="#{libroController.selected.numPagina}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_numPagina}"/>
                    <p:tooltip for="numPagina" value="#{bundle.EditLibroTitle_numPagina}" position="right"/>
                    <h:outputLabel class="form-label negrita" value="#{bundle.EditLibroLabel_descripcion}" for="descripcion"><span class="negrita" style="color:red; ">(*)</span></h:outputLabel>
                    <p:inputTextarea rows="4" cols="30" id="descripcion" value="#{libroController.selected.descripcion}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_descripcion}"/>
                    <p:tooltip for="descripcion" value="#{bundle.EditLibroTitle_descripcion}" position="right"/>
                    <h:outputLabel class="form-label negrita" value="#{bundle.EditLibroLabel_isbn}" for="isbn"><span class="negrita" style="color:red; ">(*)</span></h:outputLabel>
                    <h:inputText class="form-control" id="isbn" value="#{libroController.selected.isbn}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_isbn}"/>
                    <p:tooltip for="isbn" value="#{bundle.EditLibroTitle_isbn}" position="right"/>
                    <h:outputLabel class="form-label negrita" value="Cant. disponible: " for="cantidadDisponible"><span class="negrita" style="color:red; ">(*)</span></h:outputLabel>
                    <h:inputText class="form-control" id="cantidadDisponible" value="#{libroController.selected.cantidadDisponible}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_cantidadDisponible}"/>
                    <p:tooltip for="cantidadDisponible" value="#{bundle.EditLibroTitle_cantidadDisponible}" position="right"/>
                    
                </h:panelGrid>
                <br />
                <h:commandLink class="btn btn-success" action="#{libroController.create}"><i class="fas fa-save"></i> #{bundle.CreateLibroSaveLink}</h:commandLink>
                <br />
                <br />
                <div class="btn-toolbar">
                    <h:commandLink class="btn btn-outline-primary" action="#{libroController.prepareList}" immediate="true"><i class="fas fa-list"></i> #{bundle.CreateLibroShowAllLink}</h:commandLink>
                    <h:link class="btn btn-outline-primary" outcome="/index"><i class="fas fa-home"></i> #{bundle.CreateLibroIndexLink}</h:link>
                </div>
                <br />
                <br />
                <script>
                </script>
            </h:form>
                    </div>
                <div class="col-xl-5">
                    <img src="https://www.el-libro.org.ar/wp-content/uploads/2018/03/ed44_banneranim_300x600.gif" width="80%"/>
                </div>
            </div>
            </div>
            </div>  
            <script>
                


                PrimeFaces.locales['es'] = {
                    closeText: 'Cerrar',
                    prevText: 'Anterior',
                    nextText: 'Siguiente',
                    monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                    monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
                    dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
                    dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],
                    dayNamesMin: ['D', 'L', 'M', 'Mi', 'J', 'V', 'S'],
                    weekHeader: 'Semana',
                    firstDay: 1,
                    isRTL: false,
                    showMonthAfterYear: false,
                    yearSuffix: '',
                    timeOnlyTitle: 'Sólo hora',
                    timeText: 'Tiempo',
                    hourText: 'Hora',
                    minuteText: 'Minuto',
                    secondText: 'Segundo',
                    currentText: 'Fecha actual',
                    ampm: false,
                    month: 'Mes',
                    week: 'Semana',
                    day: 'Día',
                    allDayText: 'Todo el día'
                    };
            </script>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/libro/EditExistencias.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="#{logueo.cambiarModoLT1()}">
        <ui:define name="title">
            <h:outputText value="Editar las existencias de un material bibliográfico"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages infoClass="alert alert-success" errorClass="alert alert-danger"/>
            </h:panelGroup>
            <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
            </div>
            <div class="card-body">
            <div class="row">
                <div class="col-xl-7"> 
                <h:form id="ELibro">
                    <h:outputLabel>Para Actualizar la información de algún Libro es necesario que rellene los siguientes campos. Los campos obligatorios estan marcados con:  <span class="negrita" style="color:red; ">(*)</span></h:outputLabel>
                    <br/>
                    <br/>
                <h:panelGrid columns="3" class="col-xl-10">
                    <h:outputLabel class="form-label negrita" value="#{bundle.EditLibroLabel_id} LIBRO" for="id" />
                    <h:inputText class="form-control" id="id" value="#{libroController.selected.id}" disabled="true"/>
                    <p:tooltip for="id" value="#{bundle.EditLibroTitle_id}" position="right"/>
                    <h:outputLabel class="form-label negrita" value="#{bundle.EditLibroLabel_titulo}" for="titulo"><span class="negrita" style="color:red; ">(*)</span></h:outputLabel>
                    <h:inputText disabled="true" class="form-control" id="titulo" value="#{libroController.selected.titulo}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_titulo}"/>
                    <p:tooltip for="titulo" value="#{bundle.EditLibroTitle_titulo}" position="right"/>
                    <h:outputLabel class="form-label negrita" value="#{bundle.EditLibroLabel_idAutor}" for="idAutor" ><span class="negrita" style="color:red; ">(*)</span></h:outputLabel>
                    <p:selectOneMenu disabled="true" style="width: 300px;" filter="true" filterPlaceholder="Autor" id="idAutor" value="#{libroController.selected.idAutor}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_idAutor}">
                        <f:selectItems value="#{autorController.itemsAvailableSelectOne}"/>
                    </p:selectOneMenu> 
                    <p:tooltip for="idAutor" value="#{bundle.EditLibroTitle_idAutor}" position="right"/>
                    <h:outputLabel class="form-label negrita" value="#{bundle.EditLibroLabel_idEditorial}" for="idEditorial" ><span class="negrita" style="color:red; ">(*)</span></h:outputLabel>
                    <p:selectOneMenu disabled="true" style="width: 300px;" filter="true" filterPlaceholder="Editorial" id="idEditorial" value="#{libroController.selected.idEditorial}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_idEditorial}">
                        <f:selectItems value="#{editorialController.itemsAvailableSelectOne}"/>
                    </p:selectOneMenu>
                    <p:tooltip for="idEditorial" value="#{bundle.EditLibroTitle_idEditorial}" position="right"/>
                    <h:outputLabel class="form-label negrita" value="#{bundle.EditLibroLabel_idMateria}" for="idMateria" ><span class="negrita" style="color:red; ">(*)</span></h:outputLabel>
                    <p:selectOneMenu disabled="true" style="width: 300px;" filter="true" filterPlaceholder="Género" id="idMateria" value="#{libroController.selected.idMateria}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_idMateria}">
                        <f:selectItems value="#{materiaController.itemsAvailableSelectOne}"/>
                    </p:selectOneMenu>
                    <p:tooltip for="idMateria" value="#{bundle.EditLibroTitle_idMateria}" position="right"/>
                    <h:outputLabel class="form-label negrita" value="#{bundle.EditLibroLabel_cantidad}" for="cantidad"><span class="negrita" style="color:red; ">(*)</span></h:outputLabel>
                    <h:inputText class="form-control" id="cantidad" value="#{libroController.selected.cantidad}"  required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_cantidad}" validatorMessage="No está permitido tener menos de las existencias registradas.">
                        <f:validateLongRange minimum="#{libroController.selected.cantidad}"/>
                    </h:inputText>
                    <p:tooltip for="cantidad" value="#{bundle.EditLibroTitle_cantidad}" position="right"/>
                   
                </h:panelGrid>
                    <br/>
                    <h:commandLink class="btn btn-success" action="#{libroController.update}" ><i class="fas fa-save"></i> #{bundle.EditLibroSaveLink}</h:commandLink>
                <br />
                <br />
                <div class="btn-toolbar">
                    <h:link class="btn btn-outline-primary" outcome="View" ><i class="fas fa-file-alt"></i> Datos del libro</h:link>
                    <h:commandLink class="btn btn-outline-primary" action="#{libroController.prepareList}" immediate="true"><i class="fas fa-list"></i> Listar todos los libros</h:commandLink>
                </div>
                <br />
                <br />
                
            </h:form>
                </div>
                <div class="col-xl-5">
                    <img src="https://www.el-libro.org.ar/wp-content/uploads/2018/03/ed44_banneranim_300x600.gif" width="80%"/>
                </div>
            </div>
            </div>
            </div>  
            <script>
                PrimeFaces.locales['es'] = {
                    closeText: 'Cerrar',
                    prevText: 'Anterior',
                    nextText: 'Siguiente',
                    monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                    monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
                    dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
                    dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],
                    dayNamesMin: ['D', 'L', 'M', 'Mi', 'J', 'V', 'S'],
                    weekHeader: 'Semana',
                    firstDay: 1,
                    isRTL: false,
                    showMonthAfterYear: false,
                    yearSuffix: '',
                    timeOnlyTitle: 'Sólo hora',
                    timeText: 'Tiempo',
                    hourText: 'Hora',
                    minuteText: 'Minuto',
                    secondText: 'Segundo',
                    currentText: 'Fecha actual',
                    ampm: false,
                    month: 'Mes',
                    week: 'Semana',
                    day: 'Día',
                    allDayText: 'Todo el día'
                    };
            </script>
        </ui:define>
    </ui:composition>

</html>