src/main/java/controlador/InventarioController.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/J2EE/EJB30/StatelessEjbClass.java to edit this template
 */
package controlador;

import accesoDatos.AutorFacade;
import accesoDatos.EditorialFacade;
import accesoDatos.LibroFacade;
import archivos.InventarioCSV;
import entidades.Autor;
import entidades.Editorial;
import entidades.Libro;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import jakarta.ejb.EJB;
import jakarta.enterprise.context.SessionScoped;
import jakarta.faces.context.FacesContext;
import jakarta.inject.Named;
import jakarta.servlet.ServletOutputStream;
import jakarta.servlet.http.HttpServletResponse;
import pdf.InventarioAutoresPDF;
import pdf.InventarioEditorialPDF;
import pdf.InventarioPDF;

/**
 *
 * @author JHONATAN
 */
@Named("inventarioController")
@SessionScoped
public class InventarioController implements Serializable {

    @EJB
    private LibroFacade libroFacade;

    @EJB
    private EditorialFacade editorialFacade;

    @EJB
    private AutorFacade autorFacade;
    
    private boolean activar; // Otras formas de descarga
    
    public int getNumeroLibros(){
        return libroFacade.count();
    }
    public int getNumeroEditoriales(){
        return editorialFacade.count();
    }
    public int getNumeroAutores(){
        return autorFacade.count();
    }
    
     public void downloadFile() throws IOException {
            
            FileInputStream fis = null;
            try {
                InventarioCSV csv = new InventarioCSV(libroFacade.findAll());
                csv.generaCSV();
                File fichero= new File("Inventario.csv");
                FacesContext ctx = FacesContext.getCurrentInstance();
                fis = new FileInputStream(fichero);
                byte[] bytes = new byte[1000];
                int read = 0;
            if (!ctx.getResponseComplete()) {
                String fileName = fichero.getName();
                String contentType = "text/comma-separated-values";
                HttpServletResponse response =
                        (HttpServletResponse) ctx.getExternalContext().getResponse();
                
                response.setContentType(contentType);
                
                response.setHeader("Content-Disposition",
                        "attachment;filename=\"" + fileName + "\"");
                
                ServletOutputStream out = response.getOutputStream();
                
                while ((read = fis.read(bytes)) != -1) {
                    out.write(bytes, 0, read);
                }
                out.flush();
                out.close();
                System.out.println("\nDescargado\n");
                ctx.responseComplete();
            }       
            } catch (FileNotFoundException ex) {
                Logger.getLogger(InventarioController.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    fis.close();
                } catch (IOException ex) {
                    Logger.getLogger(InventarioController.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
}

public void downloadFilePDF() throws IOException {

        FileInputStream fis = null;
        try {
            InventarioPDF pdf = new InventarioPDF(libroFacade.findAll());
            File fichero= new File("Inventario.pdf");
            FacesContext ctx = FacesContext.getCurrentInstance();
            fis = new FileInputStream(fichero);
            byte[] bytes = new byte[1000];
            int read = 0;
            if (!ctx.getResponseComplete()) {
                String fileName = fichero.getName();
                //String contentType = "application/vnd.ms-excel";
                String contentType = "application/pdf";
                HttpServletResponse response =
                        (HttpServletResponse) ctx.getExternalContext().getResponse();
                
                response.setContentType(contentType);
                
                response.setHeader("Content-Disposition",
                        "attachment;filename=\"" + fileName + "\"");
                
                ServletOutputStream out = response.getOutputStream();
                
                while ((read = fis.read(bytes)) != -1) {
                    out.write(bytes, 0, read);
                }
                out.flush();
                out.close();
                System.out.println("\nDescargado\n");
                ctx.responseComplete();
            }       
            } catch (FileNotFoundException ex) {
                Logger.getLogger(InventarioController.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                    try {
                        fis.close();
                    } catch (IOException ex) {
                        Logger.getLogger(InventarioController.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
        }
    //Formas de descarga
    public void mostrarF(){
        activar = !activar;
    }

    public boolean isActivar() {
        return activar;
    }

    public void setActivar(boolean activar) {
        this.activar = activar;
    }
    
    
    public List<List<Libro>> ordenarEditorial(){
        List<List<Libro>> lista = new ArrayList<>();
                for(Editorial e : editorialFacade.findEditorialASC())
                    lista.add(libroFacade.findEditorial(e.getEditorial()));
        return lista;
    }
    
    public List<List<Libro>> ordenarAutor(){
        List<List<Libro>> lista = new ArrayList<>();
                for(Autor a : autorFacade.findAutorASC())
                    lista.add(libroFacade.findAutor(a.getAutor()));
        return lista;
    }

   public void downloadFileAutorPDF() throws IOException {

        FileInputStream fis = null;
        try {
            InventarioAutoresPDF pdf = new InventarioAutoresPDF(ordenarAutor());
            File fichero= new File("InventarioAutor.pdf");
            FacesContext ctx = FacesContext.getCurrentInstance();
            fis = new FileInputStream(fichero);
            byte[] bytes = new byte[1000];
            int read = 0;
            if (!ctx.getResponseComplete()) {
                String fileName = fichero.getName();
                //String contentType = "application/vnd.ms-excel";
                String contentType = "application/pdf";
                HttpServletResponse response =
                        (HttpServletResponse) ctx.getExternalContext().getResponse();
                
                response.setContentType(contentType);
                
                response.setHeader("Content-Disposition",
                        "attachment;filename=\"" + fileName + "\"");
                
                ServletOutputStream out = response.getOutputStream();
                
                while ((read = fis.read(bytes)) != -1) {
                    out.write(bytes, 0, read);
                }
                out.flush();
                out.close();
                System.out.println("\nDescargado\n");
                ctx.responseComplete();
            }       
            } catch (FileNotFoundException ex) {
                Logger.getLogger(InventarioController.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                    try {
                        fis.close();
                    } catch (IOException ex) {
                        Logger.getLogger(InventarioController.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
        }
    
    public void downloadFileEditorialPDF() throws IOException {

        FileInputStream fis = null;
        try {
            System.out.println("Preparando la descarga ....");
            InventarioEditorialPDF pdf = new InventarioEditorialPDF(ordenarEditorial());
            File fichero= new File("InventarioEditorial.pdf");
            FacesContext ctx = FacesContext.getCurrentInstance();
            fis = new FileInputStream(fichero);
            byte[] bytes = new byte[1000];
            int read = 0;
            if (!ctx.getResponseComplete()) {
                String fileName = fichero.getName();
                //String contentType = "application/vnd.ms-excel";
                String contentType = "application/pdf";
                HttpServletResponse response =
                        (HttpServletResponse) ctx.getExternalContext().getResponse();
                
                response.setContentType(contentType);
                
                response.setHeader("Content-Disposition",
                        "attachment;filename=\"" + fileName + "\"");
                
                ServletOutputStream out = response.getOutputStream();
                
                while ((read = fis.read(bytes)) != -1) {
                    out.write(bytes, 0, read);
                }
                out.flush();
                out.close();
                System.out.println("\nDescargado\n");
                ctx.responseComplete();
            }       
            } catch (FileNotFoundException ex) {
                Logger.getLogger(InventarioController.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                    try {
                        fis.close();
                    } catch (IOException ex) {
                        Logger.getLogger(InventarioController.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
        }
}

src/main/webapp/inventario/Download.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="#{logueo.cambiarModoLT1()}">
        <ui:define name="title">
            <h:outputText value="Descargar inventario en formato CSV o PDF"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages infoClass="alert alert-success" errorClass="alert alert-danger"/>
            </h:panelGroup>
            <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
            </div>
            <div class="card-body">
            <div class="row">
                <div class="col-xl-7">
                <h:form id="Descargas">
                    <h:outputLabel value="En ciertos ámbitos, la organización y el orden son indispensables para lograr el éxito. Especialmente, en el mundo empresarial se reconoce su importancia. Teniendo en cuenta esto, hemos hecho el inventario de libros del Centro de Información, en formato PDF y CSV, con el fin de que encuentres un apoyo en esta área." />
                    <br/>
                    <br/>
                <h:panelGrid columns="2" class="col-xl-7">
                    <h:outputText class="form-label negrita" value="Total de libros Registrados: "/>
                    <h:outputText class="form-control" value="#{inventarioController.numeroLibros}" title="Número de Libros en la DB."/>
                </h:panelGrid>
                <br />
                <div class="btn-toolbar">
                    <h:commandLink class="btn btn-danger text-white" style="text-decoration: none;" action="#{inventarioController.downloadFilePDF()}"><i class="fas fa-file-pdf text-white"></i> Descargar Inventario General PDF
                </h:commandLink>
                <h:commandLink class="btn btn-success text-white" style="text-decoration: none;" action="#{inventarioController.downloadFile()}"><i class="fas fa-file-csv text-white"></i> Descargar Inventario General CSV
                </h:commandLink>
                </div>
                <br/>
                <br/>
                <div class="btn-toolbar">
                    <p:commandLink id="btnA" class="btn btn-primary text-white " actionListener="#{inventarioController.mostrarF()}" update="Descargas"><i class="fas fa-plus"></i></p:commandLink>
                    <h5 class="text-black-50">Otras opciones de Descarga</h5>
                </div>
                <br/>
                <h:panelGrid columns="2" class="col-xl-7" rendered="#{inventarioController.activar}">
                    <h:commandLink class="btn btn-danger" style="text-decoration: none;" action="#{inventarioController.downloadFileAutorPDF()}"><i class="fas fa-file-pdf text-white"></i></h:commandLink>
                    <h:outputLabel class="negrita" value="Inventario de Libros por Autor"/>
                    <h:commandLink class="btn btn-danger" style="text-decoration: none;" action="#{inventarioController.downloadFileEditorialPDF()}"><i class="fas fa-file-pdf text-white"></i></h:commandLink>
                    <h:outputLabel class="negrita" value="Inventario de Libros por Editorial"/>
                </h:panelGrid>
                <br />
                <br />

            </h:form>
                    </div>
                        <div class="col-xl-5">
                            <img src="https://uem.edu.mx/wp-content/uploads/2021/01/6909-scaled-1024x732.jpg" width="100%"/>
                        </div>
                    </div>
                </div>
            </div> 
        </ui:define>
    </ui:composition>

</html>