src/main/java/controlador/LectorController.java
package controlador;

import accesoDatos.DocenteFacade;
import accesoDatos.EstudianteFacade;
import entidades.Lector;
import controlador.util.JsfUtil;
import controlador.util.PaginationHelper;
import accesoDatos.LectorFacade;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import jakarta.ejb.EJB;
import jakarta.inject.Named;
import jakarta.enterprise.context.SessionScoped;
import jakarta.faces.component.UIComponent;
import jakarta.faces.context.FacesContext;
import jakarta.faces.convert.Converter;
import jakarta.faces.convert.FacesConverter;
import jakarta.faces.model.DataModel;
import jakarta.faces.model.ListDataModel;
import jakarta.faces.model.SelectItem;

@Named("lectorController")
@SessionScoped
public class LectorController implements Serializable {

    @EJB
    private EstudianteFacade estudianteFacade;

    @EJB
    private DocenteFacade docenteFacade;

    
    private Lector current;
    private DataModel items = null;
    @EJB
    private accesoDatos.LectorFacade ejbFacade;
    
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public LectorController() {
    }

    public Lector getSelected() {
        if (current == null) {
            current = new Lector();
            selectedItemIndex = -1;
        }
        return current;
    }

    private LectorFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Lector) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Lector();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("LectorCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Lector) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("LectorUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Lector) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.info(ResourceBundle.getBundle("/Bundle").getString("LectorDeleted"));
        } catch (Exception e) {
            JsfUtil.error(ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        List mL = new ArrayList();
        mL.addAll(docenteFacade.findAll());
        mL.addAll(estudianteFacade.findAll());
        return JsfUtil.getSelectItems(mL, true);
    }
    public List getLectoresDisponibles(){
        List mL = new ArrayList();
        mL.addAll(docenteFacade.findAll());
        mL.addAll(estudianteFacade.findAll());
        return mL;
    }

    public Lector getLector(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Lector.class)
    public static class LectorControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            LectorController controller = (LectorController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "lectorController");
            return controller.getLector(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Lector) {
                Lector o = (Lector) object;
                return getStringKey(o.getIdlector());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Lector.class.getName());
            }
        }

    }

}

src/main/webapp/lector/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateLectorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateLectorLabel_idlector}" for="idlector" />
                    <h:inputText id="idlector" value="#{lectorController.selected.idlector}" title="#{bundle.CreateLectorTitle_idlector}" required="true" requiredMessage="#{bundle.CreateLectorRequiredMessage_idlector}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{lectorController.create}" value="#{bundle.CreateLectorSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{lectorController.prepareList}" value="#{bundle.CreateLectorShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateLectorIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/lector/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditLectorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditLectorLabel_idlector}" for="idlector" />
                    <h:inputText id="idlector" value="#{lectorController.selected.idlector}" title="#{bundle.EditLectorTitle_idlector}" required="true" requiredMessage="#{bundle.EditLectorRequiredMessage_idlector}"/>
                </h:panelGrid>
                <h:commandLink action="#{lectorController.update}" value="#{bundle.EditLectorSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditLectorViewLink}"/>
                <br />
                <h:commandLink action="#{lectorController.prepareList}" value="#{bundle.EditLectorShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditLectorIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/lector/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListLectorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListLectorEmpty}" rendered="#{lectorController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{lectorController.items.rowCount > 0}">
                    <h:outputText value="#{lectorController.pagination.pageFirstItem + 1}..#{lectorController.pagination.pageLastItem + 1}/#{lectorController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{lectorController.previous}" value="#{bundle.Previous} #{lectorController.pagination.pageSize}" rendered="#{lectorController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{lectorController.next}" value="#{bundle.Next} #{lectorController.pagination.pageSize}" rendered="#{lectorController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{lectorController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLectorTitle_idlector}"/>
                            </f:facet>
                            <h:outputText value="#{item.idlector}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{lectorController.prepareView}" value="#{bundle.ListLectorViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{lectorController.prepareEdit}" value="#{bundle.ListLectorEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{lectorController.destroy}" value="#{bundle.ListLectorDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{lectorController.prepareCreate}" value="#{bundle.ListLectorCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListLectorIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/lector/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewLectorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewLectorLabel_idlector}"/>
                    <h:outputText value="#{lectorController.selected.idlector}" title="#{bundle.ViewLectorTitle_idlector}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{lectorController.destroyAndView}" value="#{bundle.ViewLectorDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewLectorEditLink}"/>
                <br />
                <h:commandLink action="#{lectorController.prepareCreate}" value="#{bundle.ViewLectorCreateLink}" />
                <br />
                <h:commandLink action="#{lectorController.prepareList}" value="#{bundle.ViewLectorShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewLectorIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>